general.live_config_reload = false
general.import = ["~/.config/alacritty/colors-ayu.toml"]
general.ipc_socket = true

[env]
TERM = "xterm-256color"

[window]
dimensions = {columns = 100, lines = 24}
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 30

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 16.0

[selection]
save_to_clipboard = true

[cursor]
# style = {shape = "Beam"}
vi_mode_style = {shape = "Block"}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "0", mods = "Control", action = "ResetFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
